site_name: lightinsighter
site_description: A Comprehensive Modeling Framework Empowered by PyTorch
repo_name: lightinsighter/lightinsighter
repo_url: https://github.com/lightinsighter/lightinsighter
copyright: Copyright &copy; 2023 lightinsighter
docs_dir: wiki
site_dir: docs
site_url: https://lightinsighter.github.io/lightinsighter

nav:
  - Documentation: index.md
  - Commands: index.md

theme:
  name: material
  logo: icon.png
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.suggest
    - toc.follow
    - header.autohide
  icon:
    repo: fontawesome/brands/github
  favicon: icon.png
  palette:
    primary: white

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - codehilite
  #- callouts:
  #    strip_period: no
  - footnotes
  - md_in_html
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.tab:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "¤"

extra_css:
  - static/extra.css

plugins:
  - autorefs
  - search
  - markdown-exec
  - coverage
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            heading_level: 3
            show_root_heading: False
            show_root_toc_entry: False
            show_root_members_full_path: False
            merge_init_into_class: True
            show_docstring_examples: True
            show_bases: True
            signature_crossrefs: True
            show_signature: True
            show_signature_annotations: True
            separate_signature: True

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lightinsighter
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lightinsighter
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/lightinsighter/
    - icon: fontawesome/solid/paper-plane
      link: mailto:lightinsighter@gmail.com
